### ISSUE TITLE
Allow Plugins to register for Diff Views

### ISSUE THREAD

**Issue by andy-wm-arthur** [nautobot/nautobot-app-version-control#60]
DIff views rely on a manual mapping from ContentType to table-list-view. We must be able to look up a list view for an object in order to extend it as a diff view. 

Currently, plugins can register version-controlled-models, but can't see diffs for these models. We must allow them to register entries in the mapping in order to provide diff views.

**Comment by andrew-wm-arthur** [comment]
Addressed https://github.com/nautobot/nautobot-plugin-workflow-dolt/pull/62
